// Golden snapshot: seeded weekly plan generated by buildPlan.
//
// Excluded from snapshot:
//   day.id  — depends on Date.now(), not on RNG or inputs.
//
// All other fields serialised verbatim, including _spec (plain object,
// no functions or circular refs — confirmed by shape inspection).
//
// CURRENT_WEEK (Date-derived inside buildPlan) is neutralised by
// freeFormPool: [] — when the pool is empty that branch never fires.

import { describe, it, expect, vi } from 'vitest';
import { buildPlan } from '../buildPlan.js';
import { mulberry32 } from '../rng.js';

const SEED = 123456;

const PROFILE = {
  weight:       74,
  goal:         "maintain",     // computeStrategy → "mantenimiento_equilibrado"
  activity:     "moderate",     // PROTEIN_FACTOR.moderate — confirmed constants.js:11
  intolerances: [],
  trainingDays: [],
  extras:       {},
  mealsPerDay:  3,
  tiempoCocina: "normal",
  experiencia:  "intermedio",
  simpleMode:   false,
  dob:          "1990-01-01",   // inert inside buildPlan
  gender:       "male",         // inert inside buildPlan
  height:       178,            // inert inside buildPlan
};

const TARGET_KCAL = 2000;

const BASE_OPTS = {
  month:          5,            // June — deterministic seasonal pool
  weekNumber:     23,
  pastProteins:   {},
  freeFormPool:   [],           // neutralises CURRENT_WEEK Date dependency
  saveMealMemory: vi.fn(),
};

// Serialiser: strips day.id; keeps everything else (meals, _spec, metadata, …)
function serialiseDays(days) {
  return days.map(({ id: _id, ...rest }) => rest);
}

function run(seed) {
  return buildPlan(
    JSON.parse(JSON.stringify(PROFILE)),
    TARGET_KCAL,
    { ...BASE_OPTS, saveMealMemory: vi.fn(), rng: mulberry32(seed) },
  );
}

describe('buildPlan — golden snapshot (seeded)', () => {
  it('produces stable result.days with seed 123456', () => {
    const result = run(SEED);
    expect(serialiseDays(result.days)).toMatchSnapshot();
  });

  it('stability — two runs with seed 123456 are byte-identical', () => {
    const a = serialiseDays(run(SEED).days);
    const b = serialiseDays(run(SEED).days);
    expect(JSON.stringify(b)).toBe(JSON.stringify(a));
  });

  it('sensitivity — seed 123 vs seed 456 produce different result.days', () => {
    const a = JSON.stringify(serialiseDays(run(123).days));
    const b = JSON.stringify(serialiseDays(run(456).days));
    expect(b).not.toBe(a);
  });

  it('no opts.rng — buildPlan runs without throwing', () => {
    expect(() =>
      buildPlan(
        JSON.parse(JSON.stringify(PROFILE)),
        TARGET_KCAL,
        { ...BASE_OPTS, saveMealMemory: vi.fn() },
      )
    ).not.toThrow();
  });
});

// Sin opts.rng inyectado, buildPlan siembra _rnd con hash(userId+weekNumber)
// (buildPlan.js:26). Estos tests cubren ese camino — sin pasar rng manual.
function runSeeded(userId, weekNumber) {
  return buildPlan(
    JSON.parse(JSON.stringify(PROFILE)),
    TARGET_KCAL,
    { ...BASE_OPTS, weekNumber, userId, saveMealMemory: vi.fn() },
  );
}

describe('buildPlan — seed determinista por defecto (sin opts.rng)', () => {
  it('determinismo — mismo userId+weekNumber → days byte-idénticos (excluyendo day.id)', () => {
    const a = serialiseDays(runSeeded('user-abc', 23).days);
    const b = serialiseDays(runSeeded('user-abc', 23).days);
    expect(JSON.stringify(b)).toBe(JSON.stringify(a));
  });

  it('sensibilidad — distinto userId → days distintos', () => {
    const a = JSON.stringify(serialiseDays(runSeeded('user-abc', 23).days));
    const b = JSON.stringify(serialiseDays(runSeeded('user-xyz', 23).days));
    expect(b).not.toBe(a);
  });

  it('sensibilidad — distinto weekNumber → days distintos', () => {
    const a = JSON.stringify(serialiseDays(runSeeded('user-abc', 23).days));
    const b = JSON.stringify(serialiseDays(runSeeded('user-abc', 24).days));
    expect(b).not.toBe(a);
  });

  it('opts.rng explícito sigue ganando sobre la seed por userId+weekNumber', () => {
    const withRng = serialiseDays(run(SEED).days);
    const withoutRng = serialiseDays(runSeeded('user-abc', 23).days);
    // Distintos mecanismos de seed deben producir secuencias _rnd distintas
    // (no es una igualdad garantizada, pero confirma que rng explícito no
    // colapsa silenciosamente al mismo resultado que la seed por defecto).
    expect(JSON.stringify(withRng)).not.toBe(JSON.stringify(withoutRng));
  });
});
