// Golden snapshot: seeded weekly plan generated by buildPlan.
//
// Excluded from snapshot:
//   day.id  — depends on Date.now(), not on RNG or inputs.
//
// All other fields serialised verbatim, including _spec (plain object,
// no functions or circular refs — confirmed by shape inspection).
//
// CURRENT_WEEK (Date-derived inside buildPlan) is neutralised by
// freeFormPool: [] — when the pool is empty that branch never fires.

import { describe, it, expect, vi } from 'vitest';
import { buildPlan } from '../buildPlan.js';

// mulberry32 — deterministic PRNG. seed → () => [0, 1)
function mulberry32(seed) {
  let s = seed >>> 0;
  return function () {
    s = (s + 0x6D2B79F5) >>> 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const SEED = 123456;

const PROFILE = {
  weight:       74,
  goal:         "maintain",     // computeStrategy → "mantenimiento_equilibrado"
  activity:     "moderate",     // PROTEIN_FACTOR.moderate — confirmed constants.js:11
  intolerances: [],
  trainingDays: [],
  extras:       {},
  mealsPerDay:  3,
  tiempoCocina: "normal",
  experiencia:  "intermedio",
  simpleMode:   false,
  dob:          "1990-01-01",   // inert inside buildPlan
  gender:       "male",         // inert inside buildPlan
  height:       178,            // inert inside buildPlan
};

const TARGET_KCAL = 2000;

const BASE_OPTS = {
  month:          5,            // June — deterministic seasonal pool
  weekNumber:     23,
  pastProteins:   {},
  freeFormPool:   [],           // neutralises CURRENT_WEEK Date dependency
  saveMealMemory: vi.fn(),
};

// Serialiser: strips day.id; keeps everything else (meals, _spec, metadata, …)
function serialiseDays(days) {
  return days.map(({ id: _id, ...rest }) => rest);
}

function run(seed) {
  return buildPlan(
    JSON.parse(JSON.stringify(PROFILE)),
    TARGET_KCAL,
    { ...BASE_OPTS, saveMealMemory: vi.fn(), rng: mulberry32(seed) },
  );
}

describe('buildPlan — golden snapshot (seeded)', () => {
  it('produces stable result.days with seed 123456', () => {
    const result = run(SEED);
    expect(serialiseDays(result.days)).toMatchSnapshot();
  });

  it('stability — two runs with seed 123456 are byte-identical', () => {
    const a = serialiseDays(run(SEED).days);
    const b = serialiseDays(run(SEED).days);
    expect(JSON.stringify(b)).toBe(JSON.stringify(a));
  });

  it('sensitivity — seed 123 vs seed 456 produce different result.days', () => {
    const a = JSON.stringify(serialiseDays(run(123).days));
    const b = JSON.stringify(serialiseDays(run(456).days));
    expect(b).not.toBe(a);
  });

  it('no opts.rng — buildPlan runs without throwing', () => {
    expect(() =>
      buildPlan(
        JSON.parse(JSON.stringify(PROFILE)),
        TARGET_KCAL,
        { ...BASE_OPTS, saveMealMemory: vi.fn() },
      )
    ).not.toThrow();
  });
});
